// GENERATED by scripts/gen_training_year.py — do not edit by hand.
// Source: scripts/data/strava-year.txt (Strava export).
// Volume is hours of moving time. No coordinates are published.

export const GROUPS = ["swim", "bike", "run", "winter", "other"] as const;
export type Group = (typeof GROUPS)[number];

export interface TrainingWeek {
  /** Monday of the week, ISO date. */
  start: string;
  /** ISO week number, zero-padded. */
  w: string;
  /** Hours per group, in GROUPS order. */
  h: number[];
}

export interface Milestone {
  date: string;
  /** Index into `weeks`. */
  i: number;
  lv: string;
  en: string;
  /** Slug of the analysis sheet, when one exists. */
  sheet: string | null;
}

export const weeks: TrainingWeek[] = [
  { start: "2025-12-29", w: "01", h: [0.0, 0.89, 0.0, 3.69, 0.0] },
  { start: "2026-01-05", w: "02", h: [0.0, 0.0, 1.52, 5.38, 1.79] },
  { start: "2026-01-12", w: "03", h: [0.0, 0.0, 0.0, 7.18, 6.06] },
  { start: "2026-01-19", w: "04", h: [0.85, 0.0, 0.0, 3.95, 0.0] },
  { start: "2026-01-26", w: "05", h: [0.0, 0.0, 0.63, 6.39, 0.0] },
  { start: "2026-02-02", w: "06", h: [0.37, 0.0, 0.0, 8.14, 2.33] },
  { start: "2026-02-09", w: "07", h: [1.08, 0.0, 0.0, 5.14, 2.59] },
  { start: "2026-02-16", w: "08", h: [0.0, 0.0, 0.71, 4.75, 2.19] },
  { start: "2026-02-23", w: "09", h: [0.0, 0.0, 0.0, 6.87, 0.5] },
  { start: "2026-03-02", w: "10", h: [0.0, 0.0, 0.0, 14.18, 0.0] },
  { start: "2026-03-09", w: "11", h: [0.0, 0.75, 0.98, 4.34, 1.86] },
  { start: "2026-03-16", w: "12", h: [1.04, 3.85, 4.64, 0.0, 0.36] },
  { start: "2026-03-23", w: "13", h: [1.26, 3.11, 5.73, 0.0, 0.0] },
  { start: "2026-03-30", w: "14", h: [1.88, 6.31, 2.31, 0.0, 0.14] },
  { start: "2026-04-06", w: "15", h: [1.54, 0.09, 1.87, 0.0, 0.32] },
  { start: "2026-04-13", w: "16", h: [2.57, 13.32, 3.5, 0.0, 1.6] },
  { start: "2026-04-20", w: "17", h: [2.59, 19.67, 3.93, 0.0, 3.06] },
  { start: "2026-04-27", w: "18", h: [0.82, 5.18, 4.13, 0.0, 1.82] },
  { start: "2026-05-04", w: "19", h: [0.9, 9.47, 2.09, 0.0, 0.0] },
  { start: "2026-05-11", w: "20", h: [1.35, 1.43, 5.45, 0.0, 2.75] },
  { start: "2026-05-18", w: "21", h: [1.5, 4.42, 4.81, 0.0, 0.31] },
  { start: "2026-05-25", w: "22", h: [2.36, 2.38, 1.78, 0.0, 1.41] },
  { start: "2026-06-01", w: "23", h: [1.36, 3.6, 2.52, 0.0, 0.42] },
  { start: "2026-06-08", w: "24", h: [1.15, 4.88, 1.35, 0.0, 2.81] },
  { start: "2026-06-15", w: "25", h: [2.34, 6.7, 1.24, 0.0, 3.03] },
  { start: "2026-06-22", w: "26", h: [2.32, 6.46, 4.42, 0.0, 3.92] },
  { start: "2026-06-29", w: "27", h: [1.99, 3.12, 6.14, 0.0, 1.95] },
  { start: "2026-07-06", w: "28", h: [2.97, 8.33, 6.31, 0.0, 1.29] },
  { start: "2026-07-13", w: "29", h: [1.88, 2.73, 2.86, 0.0, 3.24] },
  { start: "2026-07-20", w: "30", h: [2.5, 5.98, 2.5, 0.0, 0.48] },
  { start: "2026-07-27", w: "31", h: [0.8, 13.26, 2.02, 0.0, 0.0] },
  { start: "2026-08-03", w: "32", h: [0.8, 7.14, 2.88, 0.0, 5.68] },
  { start: "2026-08-10", w: "33", h: [1.31, 10.6, 1.82, 0.0, 3.12] },
];

export const milestones: Milestone[] = [
  { date: "2026-03-21", i: 11, lv: "Sezonas atklāšana — 100 km", en: "Season opening — 100 km", sheet: null },
  { date: "2026-04-24", i: 16, lv: "Nometne Katalonijā", en: "Training camp in Catalonia", sheet: null },
  { date: "2026-05-17", i: 19, lv: "Rīgas maratons — 42,6 km", en: "Riga Marathon — 42.6 km", sheet: null },
  { date: "2026-06-07", i: 22, lv: "Ironman 70.3 Warsaw", en: "Ironman 70.3 Warsaw", sheet: null },
  { date: "2026-07-19", i: 28, lv: "TriKan 70.3", en: "TriKan 70.3", sheet: null },
  { date: "2026-07-25", i: 29, lv: "Tour de VidusZeme — 154 km + brick", en: "Tour de VidusZeme — 154 km + brick", sheet: "2026-07-25-tour-de-viduszeme" },
  { date: "2026-08-08", i: 31, lv: "Kuldīgas pusmaratons — 1:35:06", en: "Kuldīga half marathon — 1:35:06", sheet: null },
  { date: "2026-08-16", i: 32, lv: "141 km TT + brick", en: "141 km TT + brick", sheet: null },
];

/** Hours per group across the whole season. */
export const totals: Record<Group, number> = {
  swim: 39.5,
  bike: 143.7,
  run: 78.1,
  winter: 70.0,
  other: 55.0,
};

export const totalHours = 386.3;
export const peakWeek = 29.25;
export const activityCount = 349;
